package zw.co.hitrac.jaxcsd.api.xp;

import java.io.ByteArrayInputStream;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import zw.co.hitrac.jaxcsd.api.domain.CSD;
import zw.co.hitrac.jaxcsd.api.domain.FacilityDirectory;
import zw.co.hitrac.jaxcsd.api.domain.OrganizationDirectory;
import zw.co.hitrac.jaxcsd.api.domain.Provider;
import zw.co.hitrac.jaxcsd.api.domain.ProviderDirectory;
import zw.co.hitrac.jaxcsd.api.domain.ServiceDirectory;

/**
 *
 * @author Charles Chigoriwa
 */
public class CSDHandler {

    public static CSD getCSD(String xmlBody) throws XMLStreamException {
        CSD csd = null;
        XMLInputFactory f = XMLInputFactory.newInstance();
        XMLStreamReader r = f.createXMLStreamReader(new ByteArrayInputStream(xmlBody.getBytes()));
        while (r.hasNext()) {
            r.next();
            if (r.isStartElement()) {
                String localName = r.getLocalName();
                if ("CSD".equals(localName)) {
                    csd = new CSD();
                } else if ("organizationDirectory".equals(localName)) {
                    if (csd != null) {
                        csd.setOrganizationDirectory(new OrganizationDirectory());
                        OrganizationDirectoryHandler.handle(csd.getOrganizationDirectory(), r);
                    }
                } else if ("serviceDirectory".equals(localName)) {
                    if (csd != null) {
                        csd.setServiceDirectory(new ServiceDirectory());
                    }
                } else if ("facilityDirectory".equals(localName)) {
                    if (csd != null) {
                        csd.setFacilityDirectory(new FacilityDirectory());
                        FacilityDirectoryHandler.handle(csd.getFacilityDirectory(), r);
                    }
                } else if ("providerDirectory".equals(localName)) {
                    if (csd != null) {
                        csd.setProviderDirectory(new ProviderDirectory());
                        ProviderDirectoryHandler.handle(csd.getProviderDirectory(), r);
                    }
                }
            }

        }
        return csd;
    }

    public static void main(String[] args) throws XMLStreamException {
        CSD csd = getCSD(getXml());
        for (Provider provider : csd.getProviderDirectory().getProviders()) {
            System.out.println("oid=" + provider.getOid() + ", codedType=" + provider.getCodedTypes().get(0).getValue() + ",surname=" + provider.getDemographic().getAddresses().get(0).getAddressLines().get(0).getLine());
        }
    }

    public static String getXml() {
        String s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<CSD xmlns=\"urn:ihe:iti:csd:2013\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:ihe:iti:csd:2013 CSD.xsd\">\n"
                + "	<organizationDirectory/>\n"
                + "	<serviceDirectory/>\n"
                + "	<facilityDirectory/>\n"
                + "	<providerDirectory>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1111\">\n"
                + "			<codedType code=\"105-007\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Physician/Medical Oncology</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Banargee, Dev</commonName>\n"
                + "					<honorific>Dr.</honorific>\n"
                + "					<forename>Dev</forename>\n"
                + "					<surname>Banerjee</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-1111</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-1111</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">8909 Sunset Way</addressLine>\n"
                + "					<addressLine component=\"city\">Santa Fe</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">NM</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">87505</addressLine>\n"
                + "				</address>\n"
                + "				<gender>M</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<language code=\"bn\" codingSchema=\"BCP 47\">Bengali</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.1\"/>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1112\">\n"
                + "			<codedType code=\"105-113\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Physician/Mammographer</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>McDonald, Mary</commonName>\n"
                + "					<honorific>Dr.</honorific>\n"
                + "					<forename>Mary</forename>\n"
                + "					<surname>McDonald</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-1111</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-1111</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">8909 Sunset Way</addressLine>\n"
                + "					<addressLine component=\"city\">Santa Fe</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">NM</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">87505</addressLine>\n"
                + "				</address>\n"
                + "				<gender>F</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.1\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-005\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1113\">\n"
                + "			<codedType code=\"105-114\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Radiology Technician</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Johnson, Jack</commonName>\n"
                + "					<forename>Jack</forename>\n"
                + "					<surname>Johnson</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-2223</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-2223</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">8909 Sunset Way</addressLine>\n"
                + "					<addressLine component=\"city\">Santa Fe</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">NM</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">87505</addressLine>\n"
                + "				</address>\n"
                + "				<gender>M</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.1\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-002\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Certificate@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-005\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1114\">\n"
                + "			<codedType code=\"105-114\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Radiology Technician</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Carrara, Carla</commonName>\n"
                + "					<forename>Carla</forename>\n"
                + "					<surname>Carrara</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-1114</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-1114</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">8909 Sunset Way</addressLine>\n"
                + "					<addressLine component=\"city\">Santa Fe</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">NM</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">87505</addressLine>\n"
                + "				</address>\n"
                + "				<gender>F</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"es\" codingSchema=\"BCP 47\">Spanish</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-002\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Certificate@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-005\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1115\">\n"
                + "			<codedType code=\"105-007\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Physician/Medical Oncology</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Robertson, Robert</commonName>\n"
                + "					<forename>Robert</forename>\n"
                + "					<surname>Robertson</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-4445</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-4445</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">2887 Commerce Blvd</addressLine>\n"
                + "					<addressLine component=\"city\">Orlando</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">FL</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">32789</addressLine>\n"
                + "				</address>\n"
                + "				<gender>M</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>		\n"
                + "		\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1116\">\n"
                + "			<codedType code=\"105-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Nurse Practitioner</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Williamson, William</commonName>\n"
                + "					<forename>William</forename>\n"
                + "					<surname>Williamson</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-4445</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-4445</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">2887 Commerce Blvd</addressLine>\n"
                + "					<addressLine component=\"city\">Orlando</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">FL</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">32789</addressLine>\n"
                + "				</address>\n"
                + "				<gender>M</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>		\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1117\">\n"
                + "			<codedType code=\"105-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Nurse Practitioner</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Fredricks, Theodora</commonName>\n"
                + "					<forename>Theodora</forename>\n"
                + "					<surname>Fredricks</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">2887 Commerce Blvd</addressLine>\n"
                + "					<addressLine component=\"city\">Orlando</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">FL</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">32789</addressLine>\n"
                + "				</address>\n"
                + "				<gender>F</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1118\">\n"
                + "			<codedType code=\"105-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Nurse Practitioner</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Grant, Glena</commonName>\n"
                + "					<forename>Glenda</forename>\n"
                + "					<surname>Grant</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">8909 Sunset Way</addressLine>\n"
                + "					<addressLine component=\"city\">Santa Fe</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">NM</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">87505</addressLine>\n"
                + "				</address>\n"
                + "				<gender>F</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.1\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "		<provider oid=\"1.3.6.1.4.1.21367.200.99.1119\">\n"
                + "			<codedType code=\"105-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\">Nurse Practitioner</codedType>\n"
                + "			<demographic>\n"
                + "				<name>\n"
                + "					<commonName>Rogers, Rhonda</commonName>\n"
                + "					<forename>Rhonda</forename>\n"
                + "					<surname>Rogers</surname>\n"
                + "				</name>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"BP\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-777-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "				<contactPoint>\n"
                + "					<codedType code=\"FAX\" codingSchema=\"urn:ihe:iti:csd:2013:contactPoint\">555-888-4945</codedType>\n"
                + "				</contactPoint>\n"
                + "				<address type=\"Mailing\">\n"
                + "					<addressLine component=\"streetAddress\">2887 Commerce Blvd</addressLine>\n"
                + "					<addressLine component=\"city\">Orlando</addressLine>\n"
                + "					<addressLine component=\"stateProvince\">FL</addressLine>\n"
                + "					<addressLine component=\"country\">USA</addressLine>\n"
                + "					<addressLine component=\"postalCode\">32789</addressLine>\n"
                + "				</address>\n"
                + "				<gender>F</gender>\n"
                + "			</demographic>\n"
                + "			<language code=\"en\" codingSchema=\"BCP 47\">English</language>\n"
                + "			<organizations>\n"
                + "				<organization oid=\"1.3.6.1.4.1.21367.200.99.3\"/>\n"
                + "			</organizations>\n"
                + "			<credential>\n"
                + "				<codedType code=\"108-001\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "				<number>A_Degree@Connectathon_domain_name</number>\n"
                + "				<issuingAuthority>Connectathon_Manager</issuingAuthority>\n"
                + "				<credentialIssueDate>2013-12-01</credentialIssueDate>\n"
                + "			</credential>\n"
                + "			<specialty code=\"109-003\" codingSchema=\"1.3.6.1.4.1.21367.100.1\"/>\n"
                + "			<record created=\"2013-12-01T14:00:00+00:00\" updated=\"2013-12-01T14:00:00+00:00\" status=\"Active\" sourceDirectory=\"http://www.ihe.net\"/>\n"
                + "		</provider>\n"
                + "	</providerDirectory>\n"
                + "</CSD>";
        return s;
    }
}
